Import Libraries

In [4]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

Load Iris Dataset

In [5]:
iris = load_iris()

X = iris.data
y = iris.target

print("Dataset loaded successfully!")

Dataset loaded successfully!

Display Dataset

In [6]:
print("Feature Names:")
print(iris.feature_names)

print("\nTarget Names:")
print(iris.target_names)

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names:
['setosa' 'versicolor' 'virginica']

Convert to DataFrame

In [7]:
df = pd.DataFrame(X, columns=iris.feature_names)

df["target"] = y

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

Dataset Shape

In [8]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 150
Number of columns: 5

Check Missing Values

In [9]:
print(df.isnull().sum())

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

Statistical Description

In [10]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

Separate Features and Target

In [11]:
X = df[iris.feature_names]
y = df["target"]

Split Training and Testing Data

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 120
Testing samples: 30

Standardize Features

In [13]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Create SVM Classifier

In [14]:
svm_model = SVC(kernel="linear")

Train the Model

In [15]:
svm_model.fit(X_train_scaled, y_train)

print("SVM model trained successfully!")

SVM model trained successfully!

Make Predictions

In [16]:
y_pred = svm_model.predict(X_test_scaled)

print("Predictions completed!")

Predictions completed!

Calculate Accuracy

In [17]:
accuracy = accuracy_score(y_test, y_pred)

print("SVM Classification Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

SVM Classification Accuracy: 1.0
Accuracy Percentage: 100.0 %

Actual vs Predicted

In [18]:
result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

result

    Actual  Predicted
0        0          0
1        2          2
2        1          1
3        1          1
4        0          0
5        1          1
6        0          0
7        0          0
8        2          2
9        1          1
10       2          2
11       2          2
12       2          2
13       1          1
14       0          0
15       0          0
16       0          0
17       1          1
18       1          1
19       2          2
20       0          0
21       2          2
22       1          1
23       2          2
24       2          2
25       1          1
26       1          1
27       0          0
28       2          2
29       0          0

Display Class Names

In [19]:
result_names = pd.DataFrame({
    "Actual": iris.target_names[y_test.values],
    "Predicted": iris.target_names[y_pred]
})

result_names

        Actual   Predicted
0       setosa      setosa
1    virginica   virginica
2   versicolor  versicolor
3   versicolor  versicolor
4       setosa      setosa
5   versicolor  versicolor
6       setosa      setosa
7       setosa      setosa
8    virginica   virginica
9   versicolor  versicolor
10   virginica   virginica
11   virginica   virginica
12   virginica   virginica
13  versicolor  versicolor
14      setosa      setosa
15      setosa      setosa
16      setosa      setosa
17  versicolor  versicolor
18  versicolor  versicolor
19   virginica   virginica
20      setosa      setosa
21   virginica   virginica
22  versicolor  versicolor
23   virginica   virginica
24   virginica   virginica
25  versicolor  versicolor
26  versicolor  versicolor
27      setosa      setosa
28   virginica   virginica
29      setosa      setosa